# app/Dockerfile
FROM node:20-alpine
WORKDIR /usr/src/app

# ffmpeg for your transcode route
RUN apk add --no-cache ffmpeg

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
ENV PORT=3000
EXPOSE 3000

CMD ["node", "app.js"]