version: "3.9"
services:
  app:
    build: .
    container_name: lifelog-app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASS: apppass
      DB_NAME: lifelog
      PORT: 3000
      GEMINI_API_KEY: AIzaSyAMO_OyLp1BInE0jpdS03yrQBIxzivwAHM
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/src/app/uploads  

  db:
    image: mysql:8.0
    container_name: lifelog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lifelog
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"                    
    volumes:
      - mysqldata:/var/lib/mysql       
      - ./db/init:/docker-entrypoint-initdb.d:ro 

volumes:
  mysqldata: