
FROM node:20-alpine

RUN apk add --no-cache ffmpeg tini


WORKDIR /usr/src/app


COPY package*.json ./
RUN npm ci --omit=dev


COPY . .

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000


ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "app.js"]